In [2]:
# print("Hello in Numpy")
import numpy as np

a = np.array([22,33,44,55])
print(a)

[22 33 44 55]


In [4]:
b = np.array([[22,33,44,55],[66,77,88,99]])
print(b)

[[22 33 44 55]
 [66 77 88 99]]


In [5]:
c = np.array([[[1,2],[3,4]], [[5,6],[7,8]], [[9,10],[11,12]]])
print(c)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [8]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 4)
(3, 2, 2)


In [9]:
a.dtype

dtype('int64')

In [ ]:
d = np.array([22,33,44,55], dtype=np.float64)
print(d)

[22.  33.1 44.  55. ]


In [15]:
np.arange(1,24)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [18]:
# 4 is the step size
np.arange(1,24,4)

array([ 1,  5,  9, 13, 17, 21])

In [22]:
# np.arange(16)
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])